2016-04-25 00:07:26: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios u LEFT JOIN direcciones d on d.usuario_id=u.usuario_id WHERE  mail = siro) Unknown column 'siro' in 'where clause'' in C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(277): MysqliDb->rawQuery('SELECT  * FROM ...')
#2 [internal function]: Usuarios::login(Array)
#3 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::login', Array)
#4 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(621): Usuarios::init(Array)
#5 {main}
2016-04-25 00:40:19: exception 'Exception' with message 'Problem preparing query (SELECT  usuario_id, * FROM usuarios u LEFT JOIN direcciones d on d.usuario_id=u.usuario_id WHERE  mail = "arielcessario@gmail.com") You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* FROM usuarios u LEFT JOIN direcciones d on d.usuario_id=u.usuario_id WHERE  ma' at line 1' in C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(277): MysqliDb->rawQuery('SELECT  usuario...')
#2 [internal function]: Usuarios::login(Array)
#3 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::login', Array)
#4 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(623): Usuarios::init(Array)
#5 {main}
2016-04-25 00:44:29: exception 'Exception' with message 'Problem preparing query (SELECT usuario_id, nombre, apellido, mail, rol_id, password, tipo_doc, nro_doc, marcado, saldo FROM usuarios u LEFT JOIN direcciones d on d.usuario_id=u.usuario_id WHERE  mail = "arielcessario@gmail.com") Column 'usuario_id' in field list is ambiguous' in C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\gestion-bayres\app\includes\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(277): MysqliDb->rawQuery('SELECT usuario_...')
#2 [internal function]: Usuarios::login(Array)
#3 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::login', Array)
#4 C:\xampp\htdocs\gestion-bayres\app\bower_components\ac-angular-usuarios\includes\ac-usuarios.php(624): Usuarios::init(Array)
#5 {main}
2016-09-29 23:45:31: exception 'Exception' with message 'MySQL host is not set' in C:\xampp\htdocs\cnx\MysqliDb.php:253
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(275): MysqliDb->connect()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(1479): MysqliDb->mysqli()
#2 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#3 C:\xampp\htdocs\cnx\MysqliDb.php(707): MysqliDb->_buildQuery(NULL)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(222): MysqliDb->delete('usuarios')
#5 [internal function]: Usuarios::remove(Array)
#6 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::remov...', Array)
#7 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(638): Usuarios::init(Array)
#8 {main}
2016-10-03 22:25:21: exception 'Exception' with message 'Connect Error 1045: Access denied for user 'root'@'localhost' (using password: NO)' in /home2/arielces/public_html/cnx/MysqliDb.php:259
Stack trace:
#0 /home2/arielces/public_html/cnx/MysqliDb.php(275): MysqliDb->connect()
#1 /home2/arielces/public_html/cnx/MysqliDb.php(1479): MysqliDb->mysqli()
#2 /home2/arielces/public_html/cnx/MysqliDb.php(1095): MysqliDb->_prepareQuery()
#3 /home2/arielces/public_html/cnx/MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#4 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(247): MysqliDb->get('usuarios')
#5 [internal function]: Usuarios::get(Array)
#6 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#7 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(640): Usuarios::init(Array)
#8 {main}
2016-10-03 22:25:39: exception 'Exception' with message 'Connect Error 1045: Access denied for user 'root'@'localhost' (using password: NO)' in /home2/arielces/public_html/cnx/MysqliDb.php:259
Stack trace:
#0 /home2/arielces/public_html/cnx/MysqliDb.php(275): MysqliDb->connect()
#1 /home2/arielces/public_html/cnx/MysqliDb.php(1479): MysqliDb->mysqli()
#2 /home2/arielces/public_html/cnx/MysqliDb.php(1095): MysqliDb->_prepareQuery()
#3 /home2/arielces/public_html/cnx/MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#4 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(247): MysqliDb->get('usuarios')
#5 [internal function]: Usuarios::get(Array)
#6 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#7 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(640): Usuarios::init(Array)
#8 {main}
2016-10-03 22:25:40: exception 'Exception' with message 'Connect Error 1045: Access denied for user 'root'@'localhost' (using password: NO)' in /home2/arielces/public_html/cnx/MysqliDb.php:259
Stack trace:
#0 /home2/arielces/public_html/cnx/MysqliDb.php(275): MysqliDb->connect()
#1 /home2/arielces/public_html/cnx/MysqliDb.php(1479): MysqliDb->mysqli()
#2 /home2/arielces/public_html/cnx/MysqliDb.php(1095): MysqliDb->_prepareQuery()
#3 /home2/arielces/public_html/cnx/MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#4 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(247): MysqliDb->get('usuarios')
#5 [internal function]: Usuarios::get(Array)
#6 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#7 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(640): Usuarios::init(Array)
#8 {main}
2016-10-03 22:25:44: exception 'Exception' with message 'Connect Error 1045: Access denied for user 'root'@'localhost' (using password: NO)' in /home2/arielces/public_html/cnx/MysqliDb.php:259
Stack trace:
#0 /home2/arielces/public_html/cnx/MysqliDb.php(275): MysqliDb->connect()
#1 /home2/arielces/public_html/cnx/MysqliDb.php(1479): MysqliDb->mysqli()
#2 /home2/arielces/public_html/cnx/MysqliDb.php(1095): MysqliDb->_prepareQuery()
#3 /home2/arielces/public_html/cnx/MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#4 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(247): MysqliDb->get('usuarios')
#5 [internal function]: Usuarios::get(Array)
#6 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#7 /home2/arielces/public_html/mesero-test-componentes/bower_components/mv-angular-usuarios/includes/ac-usuarios.php(640): Usuarios::init(Array)
#8 {main}
2016-12-01 01:40:16: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id IN ( ) ) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(248): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(882): Usuarios::init(Array)
#6 {main}
2016-12-01 01:40:23: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id IN ( ) ) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(248): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(882): Usuarios::init(Array)
#6 {main}
2016-12-01 01:40:51: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id IN ( ) ) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(248): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(882): Usuarios::init(Array)
#6 {main}
2016-12-01 01:41:45: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id IN ( ) ) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(248): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(882): Usuarios::init(Array)
#6 {main}
2016-12-01 01:43:30: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id IN ( ) ) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(248): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(882): Usuarios::init(Array)
#6 {main}
2016-12-01 01:51:43: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id  NULL) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(256): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(890): Usuarios::init(Array)
#6 {main}
2016-12-01 01:53:16: exception 'Exception' with message 'Problem preparing query (SELECT  * FROM usuarios WHERE  rol_id  NULL) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(1095): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\cnx\MysqliDb.php(550): MysqliDb->_buildQuery(NULL)
#2 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(256): MysqliDb->get('usuarios')
#3 [internal function]: Usuarios::get(Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#5 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(890): Usuarios::init(Array)
#6 {main}
2016-12-12 13:38:15: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:38:23: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:39:32: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:39:56: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:40:04: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:40:10: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
2016-12-12 13:40:27: exception 'Exception' with message 'Problem preparing query (SELECT
                                    u.usuario_id,
                                    u.nombre,
                                    u.apellido,
                                    u.mail,
                                    u.nacionalidad_id,
                                    u.tipo_doc,
                                    u.nro_doc,
                                    u.comentarios,
                                    u.marcado,
                                    u.telefono,
                                    u.fecha_nacimiento,
                                    u.profesion_id,
                                    u.saldo,
                                    u.password,
                                    u.rol_id,
                                    u.news_letter,
                                    u.cbu,
                                    u.social_login,
                                    u.status,
                                    u.cta_cte,
                                    d.direccion_id,
                                    d.calle,
                                    d.nro,
                                    d.piso,
                                    d.puerta,
                                    d.ciudad_id
                                FROM usuarios u LEFT JOIN direcciones d ON d.usuario_id = u.usuario_id
                                WHERE u.rol_id IN (2) ORDER BY u.apellido, u.nombre) Unknown column 'u.cta_cte' in 'field list'' in C:\xampp\htdocs\cnx\MysqliDb.php:1482
Stack trace:
#0 C:\xampp\htdocs\cnx\MysqliDb.php(382): MysqliDb->_prepareQuery()
#1 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(296): MysqliDb->rawQuery('SELECT\r\n       ...')
#2 [internal function]: Usuarios::get(Array)
#3 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(26): call_user_func('Usuarios::get', Array)
#4 C:\xampp\htdocs\mesero-test-componentes\app\bower_components\mv-angular-usuarios\includes\ac-usuarios.php(884): Usuarios::init(Array)
#5 {main}
